name: redescomunicacionais
description: "A new Flutter project."

publish_to: 'none' 

version: 2.6.3+34

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  firebase_core: ^4.7.0
  get: ^4.6.6
  get_storage: ^2.1.1
  animated_splash_screen: ^1.3.0
  sign_in_button: ^5.0.0
  font_awesome_flutter: ^11.0.0
  cloud_firestore: ^6.3.0
  google_sign_in: ^7.2.0
  firebase_storage: ^13.3.0
  firebase_auth: ^6.4.0
  flutter_svg: ^2.0.16
  vertical_card_pager: ^1.6.2
  webview_flutter: ^4.10.0
  awesome_dialog: ^3.2.1
  url_launcher: ^6.3.1
  flutter_markdown: ^0.7.6
  flutter_quill: ^11.5.1
  image_picker: ^1.1.2
  image_cropper: ^12.2.1
  image: ^4.5.4
  intl: ^0.20.2
  package_info_plus: ^10.2.1
  geolocator: ^14.0.2
  geocoding: ^4.0.0
  connectivity_plus: ^6.1.5
  internet_connection_checker_plus: ^3.0.0
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  youtube_player_flutter: ^9.1.2
  sign_in_with_apple: ^8.1.0
  flutter_image_compress: ^2.4.0
  uuid: ^4.5.3
  firebase_remote_config: ^6.5.3
  in_app_update: ^5.0.0
  pointycastle: ^4.0.0
  flutter_secure_storage: ^10.3.1
  nearby_connections: ^4.3.0
  permission_handler: ^13.0.2
  
  flutter_localizations:
    sdk: flutter
  cloud_functions: ^6.5.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_launcher_icons: ^0.14.3
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.0.5
  hive_generator: ^2.0.1
  build_runner: ^2.4.12
  
flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  background_color_ios: "#ffffff"
  image_path: "assets/icons/rcl-blue-logo.png"
  min_sdk_android: 21
  web:
    generate: true
    image_path: "assets/icons/rcl-blue-logo.png"
    background_color: "#ffffff"
    theme_color: "#ffffff"

flutter_native_splash:
  color: "#000000" 
  image: "assets/icons/rcl-blue-logo.png"
  android: true 
  ios: true 
  web: true
  fullscreen: true 

  android_12:
    icon_background_color: "#FFFFFF"
    image: "assets/icons/rcl-blue-logo.png"
    icon_background_color_dark: "#1a1a1a"
    image_dark: "assets/icons/rcl-blue-logo.png"

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/icons/
    - assets/images/
    - assets/images/cidades/