// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCwVD8EIzUf6Ootp_HWpzs_vhGW9wmoLOI',
    appId: '1:792922518433:web:96a1cf1e3bbc23e0c891e0',
    messagingSenderId: '792922518433',
    projectId: 'redescomunicacionais',
    authDomain: 'redescomunicacionais.firebaseapp.com',
    storageBucket: 'redescomunicacionais.firebasestorage.app',
    measurementId: 'G-66ZBD4W7PG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBO5t2GpdYhX_fQPbHc4YNOK--d6a3qekk',
    appId: '1:792922518433:android:2d8f211e08c11333c891e0',
    messagingSenderId: '792922518433',
    projectId: 'redescomunicacionais',
    storageBucket: 'redescomunicacionais.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyASdAOnfc6TSY8bdMv0azXa_gRjG0L7NJY',
    appId: '1:792922518433:ios:e3d576ed741b3a8dc891e0',
    messagingSenderId: '792922518433',
    projectId: 'redescomunicacionais',
    storageBucket: 'redescomunicacionais.firebasestorage.app',
    androidClientId: '792922518433-0tul09c6dofgcsmp6fs6a8unq93l2g5u.apps.googleusercontent.com',
    iosClientId: '792922518433-2eueup5n0tiqvbc3jonpn71iciga2glo.apps.googleusercontent.com',
    iosBundleId: 'br.uff.sti.redescomunicacionais',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyASdAOnfc6TSY8bdMv0azXa_gRjG0L7NJY',
    appId: '1:792922518433:ios:e3d576ed741b3a8dc891e0',
    messagingSenderId: '792922518433',
    projectId: 'redescomunicacionais',
    storageBucket: 'redescomunicacionais.firebasestorage.app',
    androidClientId: '792922518433-0tul09c6dofgcsmp6fs6a8unq93l2g5u.apps.googleusercontent.com',
    iosClientId: '792922518433-2eueup5n0tiqvbc3jonpn71iciga2glo.apps.googleusercontent.com',
    iosBundleId: 'br.uff.sti.redescomunicacionais',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDKDmh4IdRvqvf5WQ5pGKsVZ4-LauloxjE',
    appId: '1:792922518433:web:6776e7c1c1b20a9fc891e0',
    messagingSenderId: '792922518433',
    projectId: 'redescomunicacionais',
    authDomain: 'redescomunicacionais.firebaseapp.com',
    storageBucket: 'redescomunicacionais.firebasestorage.app',
    measurementId: 'G-M9WZG96DY4',
  );

}